language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: bMkwpGlA3FNKV7THrtftnnn3qTuZ/+B1PyIEjpNRKNO9wEflniOAIRrFdM/CxioxIIcp4t28MqxHbxEHBCdnfTmQgh6Ci+1PgohX3cYpTd6vAoNY9VgMiM6+8PxyHgWDW+09jP7SZXUrIzneo69cFtwhIo20iYOdMzWVIYFgeFp2Nf5yrLb3QVOdqK+FxXlXDY+nFVZpIVT4r1nWFKQkm2oVdNS4edu9uhwTzPmFDoMutHoWnrVgfiIcWCfpcCuQSAWy7PmveZQWWyMvoIrkTNLFuj72a8WWo2Y9Maxs8d8Gi0HMGwgkMgWXJNV+obzQt+flVkpwK+Oh19wts6cxxebrTKc9hQFnhS8RVJ6Er9aMmsq0Z435aObjyGTBmLiW5JQLwo07pc2GS3yqChOHScV7M0EkA3qQc2ZSS7e/Z/clronfymN7WC6RPANbpMQIkIS8iWft0R3rhFfjwPxY1JN4gmVUwJPyJZh5DaOF9PwpqFSLm7zyeNJRM+Ubicxd6K3FvmMtQYaKpi8rlcdhvkkznN3Rgaqa+MqIvbjMbFAk6spVhzNYIbfWsxiVEk8shQdbrs97E1E0lXqIJ5poNGX5kUOlxs9rKlOs7Sshx7HlMi5vNMy+Aq1U6ociPjRZMhLej7icQFGTDpOliNhttvcXh1YGUIbyU/a0pI9ipCY=
  file: imageService-distribution.zip
  skip_cleanup: true
  on:
    branch: master
    repo: dermoritz/imageservice
